[theme]
base = "light"                                                                                                                                                             
primaryColor = "#0a58c3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f4"
textColor = "#212121"
font = "poppins"
